In [1]:
import numpy as np

In [2]:
# Assign a small array to variable a
a = np.array([[1,1,2],[3,5,8]])

In [3]:
a

array([[1, 1, 2],
       [3, 5, 8]])

## Types
Every object in python has a **type**, the type tells us what kind of object it is 
Can also call the type of an object, the **class** of an object 

In [4]:
print(a)
# check the type/class of a variable/object by using `type` function
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [5]:
print(a[0,0])

# check the type of an entry on the array by indexing 
type(a[0,0])


1


numpy.int64

Notice that `type(a[0,0])` is `numpy.int64` and not just the standard python integer type. It is telling us that 1 is an integer stored as a 64-bit number. It is a smaller integer type that saves memory

In [6]:
print(a[1,1])

5


`print` was our first example of a Python function. Functions take in a set of arguments, separated by commas, and use those arguments to create an output. There are several built-in funcions in Python, most of them are for interacting with the Python basic data types such as int (integers), float (decimal numbers), str (strings), and bool (boolean values).

In [7]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


What we obtain is a docstring, a special type of comment that is used to document how a function (or class, or module) works. The first line in the docstring is telling us the function name followed by all of its arguments in parentheses. Then there is a short description of what the function does. And finally a list of the arguments and a brief explanation about each of them.

You can see there are different types of arguments inside the parenthesis. Roughly speaking, a function has two types of arguments:

non-optional arguments: arguments you need to specify for the function to do something, and

optional arguments: arguments that are pre-filled with a default value by the function, but you can override them. Optional arguments appear inside the parenthesis () in the form optional_argument = default_value.


end is a parameter in print with the default value a new line. We can pass the value ^_^ to this parameter so that finishes the line with ^_^ instead:

In [8]:
print('changing the default end argument of the print function', end=' ^_^')

changing the default end argument of the print function ^_^

## Attributes and methods 

An object in python has attributes and methods. 

- **attribute** is a property of the object, some piece of info about it 
- **method** is a procedure associated with an object, so it is an action where the main ingredient is the object

### Check-in 

fish attributes: 
- length, color, species
- die(), bite(), swim()

**Examples**
Attributes for `numpy.arrays`

We can access a variable's attributes and methods by adding a period `.` at the end of the variable's name

`varible.method` or `variable.attribute`

In [10]:
a.shape

(2, 3)

In [12]:
type(a.shape) # example that attribute 'shape' hasits own types

tuple

In [14]:
# Methods examples
# min() returns the minimum value along specified axis 
a.min(axis=0)

array([1, 1, 2])

# Check-in

We can also call the min method without any parameters:

In [17]:
a.min() # we are able to run method with and without parameters so the parameters in this method are optional

1

Remember: methods are functions associated with an object

In [18]:
type(a.min)

builtin_function_or_method

## Exercise

1. Read the `print` function help. What is the **type of the argument `sep`? Is this optional or non-optional argument? why?

2.  Create two new variables, one with integer value 77 and another with the string 99

3. Use your variables to print `77%99%77` by changing value of one of optional parameters in `print`

In [28]:
?print 

# sep is  a optional parameter

cat = 77
rat = '99' 

print(cat,rat,cat, sep = '%') # the parameter type of 'sep' is string



Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


77%99%77
