# Python Review

## Libraries

`library` is collection of code used to perform specific tasks in our programs
- can be single file or several
- `NumPy`--> core library for numerical computing in Python
- will be using libraries that use `NumPy` arrays as their building blocks
- `NumPy` objects are optimized for processing = fast computations and less memory used


## Packages

`package` is a specific way of organizing multiple files of code into a directory hierarchy, often within a large code library 
- 'library' and 'package' can be used interchangeably --> `NumPy` is both library and package


In [2]:
import numpy as np # by importing, all objects and functions in numpy lib are made available 

## Variables

variables are names we assign to particular object in Python

In [4]:
# assign an array to a variable
a = np.array([[1,1,2],[3,5,8]])

Can view variable by running cell with name or using `print` function 

In [5]:
# show the variable
a

array([[1, 1, 2],
       [3, 5, 8]])

In [6]:
# print the variable
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

`object` is a bundle of properties and actions about something specific 
For example, object could be a data frame with properties such as number of rows, names of cols, and date created, and actions like selecting one row or add new col.

`variable` is name we give to specific `object`. same object can be referenced by different variables. Example: the sun (object) is called sol and soleil, but both refer to the same object.

## Types

Every object in Python has a `type` (also called `class`), type = what kind of object.


In [7]:
print(a) 
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The `numpy.ndarray` is the core object/data in the numpy package. can check data type of an entry int he array by indexing.

In [9]:
print(a[0,0]) # coordinates to find value within thee array
type(a[0,0]) # int64 is Python's integer type. 

1


numpy.int64

## Functions

`functions` take in a set of arguments separated by commas, and use those arguments to create an output.
In class, we will use `argument` and `parameter` interchangeably but in reality they have slightly different meanings 

`parameter` is a variable in the function definition that accepts an argument passed to the function. it is a placeholder in the function that will receive the value of an argument when the function is called.

For example:


In [13]:
def my_function(parameter1, parameter2) :
    return parameter1 + parameter2

In [14]:
result = my_function(5,10)

we can ask for info about what a function does by executing `?` followed by the function name:

In [15]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

we obtain a `docstring` --> a special type of comment that is used to document how a function (or class, or module) works. the first line in the docstring is telling us the function name followed by all of its arguments in parenthesis

there are different types of arguments:
`non-optional arguments`: arguments you need to specify for the function to do something 
`optional arguments`: arguments are pre-filled with default value by the function, but you can override them. optional arguments appear inside parenthesis () in the form of `optional_argument` =  `default_value`

#### Example

`end` is a parameter in `print` with the default value = a new line. we can pass the value (: to this parameter so that it finishes the line with (: instead

In [3]:
print('changing the default argument of the print function', end = ' (:')

changing the default argument of the print function (:

Notice that before we had always used `print` without specifying any value for the end parameter.

## Attributes and Methods

An object in Python has attributes and methods.

`method` is a procedure associated with an object so it is an action where the main ingredient is the object
`attribute` is a property of the object, a piece of information

- class = cat
- attributes = color, name, age, weight
- methods = meow(), nap(), chase_laser()

More formally, a method is a function that acts on the object it is part of

#### Examples of Attributes

In [16]:
# NumPy arrays have many methods and attributes. 

# a 3x3 array
var = np.array(([1,2,3],[4,5,6],[7,8,9]))

var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# T is an example of attribute, it returns the transpose of var

print(var.T)
print(type(var.T))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
<class 'numpy.ndarray'>


In [18]:
# shape is another attribute that tells us the shape of the array

print(var.shape)
print(type(var.shape))

(3, 3)
<class 'tuple'>


In [19]:
# ndim is attribute holding the number of array dimensions
print(var.ndim)
print(type(var.ndim))

2
<class 'int'>


Notice that attributes can have many different data types. Above we saw a `tuple` and an `int` (two of the basic Python classes) and also a NumPy array as attributes of `var`

#### Examples of Methods

In [20]:
# tolist method returns array as nested list of scalars:
var.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
# the min method returns min value in the array along specified axis
var.min(axis = 0)

# we can also call the min method without parameters, meaning that the axis param is optional
var.min()

np.int64(1)

In [23]:
# can confirm methods are functions associated to an object by checking type()
type(var.tolist)


builtin_function_or_method

In [24]:
type(var.min)

builtin_function_or_method